### ISSUE TITLE
Invisible text on public login page with 'winter' 

### ISSUE THREAD

**Issue by patrickmj** [omeka/theme-seasons#24]
With the winter theme, on /users/login (when not logged in), the Go to home page and Lost your password text are pretty much invisible

**Comment by kimisgold** [comment]
So the annoying thing about Seasons is how its matted style relies on the `#primary` container as the generic wrapper for content. It's been nice that most of the plugins have been consistent in their inclusion of that wrapper, but I understand it's not listed as a requirement anywhere and thus it shouldn't be expected.

We have two options here:
1) I provide styles for views that don't utilize the `#primary` wrapper that has the white background. 
2) GuestUser uses the `#primary` wrapper for that view.

**Comment by patrickmj** [comment]
That page is not actually produced by Guest User. It's a core view that GU just links to.
