### ISSUE TITLE
Invisible textareas in autumn theme

### ISSUE THREAD

**Issue by patrickmj** [omeka/theme-seasons#25]
The background color for textareas in autumn is the same as the rest of the page's background color, making the textarea invisible

**Comment by kimisgold** [comment]
When I checked back in on this issue, textarea elements have the same background as any other text input.

<img width="634" alt="screen shot 2016-01-08 at 3 10 40 pm" src="https://cloud.githubusercontent.com/assets/606764/12208304/0bf89662-b61a-11e5-9d88-2a86d02224a5.png">
