### ISSUE TITLE
Testing: Guest User login styled properly, form labels are bold

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-seasons#26]
Test that updates address issue #24, and that advanced search form labels are bold.

**Comment by mebrett** [comment]
On Winter, the "Go to home page" text is readable in safari but not Firefox or Chrome. Neither is "lost your password" once I'd clicked on it, so it seems to be something about the color of a visited link?

**Comment by mebrett** [comment]
Advanced search form labels all display as bold across Chrome, Safari, and Firefox, in every theme color scheme.
