### ISSUE TITLE
Autumn: no clear definition of fields on guest user login page

### ISSUE THREAD

**Issue by mebrett** [omeka/theme-seasons#27]
When the Seasons theme is set to Autumn, the fields for username and password on /users/login don't have any visual markers to differentiate them from the background.

![screen shot 2016-01-21 at 1 36 58 pm](https://cloud.githubusercontent.com/assets/2314070/12490687/c792a334-c044-11e5-8c78-f469751ed447.png)

**Comment by kimisgold** [comment]
I think this was covered in #24 and I'd missed this issue.
