### ISSUE TITLE
Test that large logo images stay within page width

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-seasons#29]
I noticed that the logo file image at http://latinahistoryproject.omeka.net/ was breaking out of the page containers at narrower screen widths. The logo file wasn't really meant to stretch to the full width of the page, with a maximum width of 2/3 of the page. Test that ce50bda constrains the logo file to its container width.

**Comment by mebrett** [comment]
Any particular version of Omeka core I should be testing this against?

**Comment by kimisgold** [comment]
Nope! Latest version should be fine, and the change should be on the seasons master branch.

**Comment by mebrett** [comment]
Logo file images now take up 2/3 of the header on a regular browser window, and do not overlap with the search bar as previously. When the window gets very small, they stack. Tested on Mac: Chrome, Safari, Firefox; on PC: IE, Chrome, Firefox

Full-width: 
![screen shot 2017-04-14 at 10 34 57 am](https://cloud.githubusercontent.com/assets/2314070/25046192/2b88d852-20fe-11e7-8e5b-9330767fbe23.png)

Narrow screen: 
![screen shot 2017-04-14 at 10 35 07 am](https://cloud.githubusercontent.com/assets/2314070/25046198/301cf33a-20fe-11e7-80a3-f801ac855f02.png)
